
run:
	@npm run dev;

build:
	@npm run build;

install:
	@echo "Install Dependencies";


#github push 
push: .gitignore
	@git add . ;
	@git commit -m "update app";
	@git push;

#gitlab push 
gitlab_push: .gitignore
	@git push gitlab main;

