
run:
	@npm run dev;

build:
	@npm run build;

install:
	@echo "Install Dependencies";


push: .gitignore
	@git add . ;
	@git commit -m "update app";
	@git push;


gitlab_push: .gitignore
	@git push gitlab main;

